import unittest
import os
import sys
import pickle

sys.path.append(os.path.join(os.path.dirname(__file__), "Flask"))

from app import app, MODEL_PATH

class FlaskAppTestCase(unittest.TestCase):
    def setUp(self):
        # Configure application for testing
        app.config["TESTING"] = True
        self.client = app.test_client()

    def test_model_pkl_exists(self):
        """
        Verify that the HDI.pkl file was generated by train.py and is in the correct place.
        """
        self.assertTrue(os.path.exists(MODEL_PATH), f"Model file not found at: {MODEL_PATH}")

    def test_home_route(self):
        """
        Verify home route returns status 200.
        """
        response = self.client.get("/")
        self.assertEqual(response.status_code, 200)
        self.assertIn(b"HDI Predictor", response.data)
        self.assertIn(b"Predicting Global", response.data)

    def test_prediction_form_route(self):
        """
        Verify Prediction route renders form.
        """
        response = self.client.get("/Prediction")
        self.assertEqual(response.status_code, 200)
        self.assertIn(b"Select Country", response.data)
        self.assertIn(b"Life Expectancy", response.data)

    def test_prediction_execution(self):
        """
        Perform a simulated form submission with test parameters and verify result values.
        """
        # Test values: Norway (encoded 131 or similar, we use code 0 for testing),
        # Life expectancy=81.7, Mean schooling=12.7, GNI=67614, Internet=86.8
        form_data = {
            "Country": "0",
            "Life expectancy": "81.7",
            "Mean years of schooling": "12.7",
            "Gross national income (GNI) per capita": "67614",
            "Internet users": "86.8"
        }
        
        response = self.client.post("/predict", data=form_data)
        self.assertEqual(response.status_code, 200)
        self.assertIn(b"Prediction Outcome", response.data)
        self.assertIn(b"HDI Score", response.data)
        
        # Verify classification category exists
        self.assertTrue(
            b"Development" in response.data or b"Out of Range" in response.data,
            "Response should contain classification badges."
        )

    def test_predict_get_redirect(self):
        """
        Verify GET on /predict redirects to /Prediction form.
        """
        response = self.client.get("/predict")
        self.assertEqual(response.status_code, 302)
        self.assertTrue(response.location.endswith("/Prediction"))

if __name__ == "__main__":
    unittest.main()
